### ISSUE TITLE
Lack of suburb leads to geocoding errors

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/port_pirie_regional_council_sa_development_applications#2]
One example that's been brought to our attention - https://www.planningalerts.org.au/applications/1041265 - Google has interpreted this as being in Mt Waverly, Victoria

In this particular case it looks like "21 Bowman St, Crystal Brook" gives better results than "21 Bowman St, Institute Hall"

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ebvp)

**Comment by MichaelBone** [comment]
I've updated the way addresses are parsed so this scraper now uses the street name (and hundred name if it is available) to make a best guess at what the suburb name should be.  In the case of "Bowman Street" it now derives "Crystal Brook" as the suburb name.  So that should resolve this issue.

**Comment by LoveMyData** [comment]
Stopped AutoRun at the moment until a new PR

**Comment by LoveMyData** [comment]
Fixed with commit - https://github.com/planningalerts-scrapers/port_pirie_regional_council_sa_development_applications/commit/5debdc55456710d5a2232fa94bd088fc93cb08f5

Re-enabled - Auto Run
